trigger: none

extends:
    template: /eng/pipelines/templates/stages/archetype-sdk-tests.yml
    parameters:
      BuildTargetingString: azure-ai-formrecognizer
      ServiceDirectory: formrecognizer
      TestTimeoutInMinutes: 200
      MatrixReplace:
        - TestSamples=.*/true
      SupportedClouds: 'Public,UsGov,China'
      Clouds: 'Prod'
      # This is a specific request from the formrecognizer service team
      # their claim is that the full matrix ends up stress-testing their service.
      # As such, the canary test runs should run on a reduced matrix.
      CloudConfig:
        Prod:
          ServiceConnection: azure-sdk-tests
          Location: 'centraluseuap'
        Public:
          SubscriptionConfiguration: $(sub-config-azure-cloud-test-resources)
          Location: 'westus2'
        UsGov:
          SubscriptionConfiguration: $(sub-config-gov-test-resources)
        China:
          SubscriptionConfiguration: $(sub-config-cn-test-resources)
      EnvVars:
        AZURE_SUBSCRIPTION_ID: $(provisioner-subscription)
        TEST_MODE: 'RunLiveNoRecord'
        AZURE_SKIP_LIVE_RECORDING: 'True'
        AZURE_TEST_RUN_LIVE: 'true'
        # Set fake authority host to ensure Managed Identity fail for Default Azure Credential
        # so "execute samples" step correctly picks up Powershell credential.
        AZURE_POD_IDENTITY_AUTHORITY_HOST: "FakeAuthorityHost"
