trigger: none

variables:
  PythonVersion: '3.9'

jobs:
  - job: 'rpat'
    displayName: 'Run Proxy and Test'

    pool:
      vmImage: 'windows-2019'

    steps:
      - task: UsePythonVersion@0
        displayName: 'Use Python $(PythonVersion)'
        inputs:
          versionSpec: $(PythonVersion)

      - pwsh: |
          choco --version
        displayName: "Is Choco available?"
        continueOnError: true

      - pwsh: |
          dir env:
        displayName: "Dump Env"

      - pwsh: |
          Get-ChildItem -Recurse "C:/Program Files/Docker"
        displayName: 'Dump Details of Docker Install'
        continueOnError: true

      - pwsh: |
          choco install docker-desktop
        displayName: 'Install docker-cli only'

      - pwsh: |
          C:\ProgramData\chocolatey\lib\docker-desktop\tools\dockercli.exe -SwitchDaemon
        displayName: 'Install docker-cli only'

      - pwsh: |
          docker run `
            --detach `
            -v $(Build.SourcesDirectory):/etc/testproxy `
            -p 5001:5001 `
            -p 5000:5000 `
            azsdkengsys.azurecr.io/engsys/ubuntu_testproxy_server:latest
        displayName: 'Run the docker container'

      - pwsh: |
          docker container ls -a
        displayName: "View running docker containers"
        continueOnError: true

      - pwsh: |
          Invoke-WebRequest -Uri "http://localhost:5000/Info/Available"
        displayName: 'http://localhost:5000/Info/Available'
        continueOnError: true

      - pwsh: |
          Invoke-WebRequest -Uri "https://localhost:5000/Info/Available"
        displayName: 'https://localhost:5000/Info/Available'
        continueOnError: true

      - pwsh: |
          Invoke-WebRequest -Uri "http://localhost:5001/Info/Available"
        displayName: 'http://localhost:5001/Info/Available'
        continueOnError: true

      - pwsh: |
          Invoke-WebRequest -Uri "https://localhost:5001/Info/Available"
        displayName: 'https://localhost:5001/Info/Available'
        continueOnError: true